language: python
dist: xenial
cache:
  pip: true
env:
  global: OPENBLAS_NUM_THREADS=1

python:
  - "3.7"

install:
  # Install mnefun
  - pip install numpy scipy matplotlib pyyaml patsy pytest pytest-cov pytest-sugar codecov flake8 pydocstyle https://api.github.com/repos/mne-tools/mne-python/zipball/master
  - pip install -ve .

script:
  - pytest mnefun
  - make flake
  # make pydocstyle  # someday, currently too bad

after_script:
  - codecov
